stages:
- test

test:
  stage: test
  script:
    - whoami
    - pwd
    - "virtualenv testvenv"
    - ". testvenv/bin/activate"
    - "python -m pip install --upgrade pip"
    - "pip install -r requirements.txt"
    - "bash run_tests.sh"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - bla_local
